force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <label>Widget</label>
    <nameField>
        <displayFormat>WIDGET-{0000}</displayFormat>
        <label>Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Widget__c/fields/Batch_Updated__c.field-meta.xml
<CustomField>
    <fullName>Batch_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/fields/Is_Properly_Nested__c.field-meta.xml
<CustomField>
    <fullName>Is_Properly_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Properly Nested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/WidgetTriggerHandler.cls
/**
 * @description       : Nesting Challenge - Enpal
 * @author            : junior95lima@gmail.com 
 * @group             : 
 * @last modified on  : 07-20-2021
 * @last modified by  : junior.lima
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   07-17-2021   junior95lima@gmail.com   Initial Version
**/
public class WidgetTriggerHandler {
       public static void adjustRecords(List<Widget__c> widgetList) {
        for (Widget__c unitWidget : widgetList) {
            if(unitWidget.Batch_Updated__c){
                /** USE THE GLOBAL MATCHER TO DEFINE IF IT IS NESTED OR NOT **/
                unitWidget.Is_Properly_Nested__c = WidgetNestedValidation.matcherLoop(unitWidget.Value__c);
            }
        }
    }
}