force-app/main/default/objects/Widget__c/Widget__c.object-meta.xml
<CustomObject>
    <label>Widget</label>
    <nameField>
        <displayFormat>WIDGET-{0000}</displayFormat>
        <label>Widget Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Widgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Widget__c/fields/Batch_Updated__c.field-meta.xml
<CustomField>
    <fullName>Batch_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Batch Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/fields/Is_Properly_Nested__c.field-meta.xml
<CustomField>
    <fullName>Is_Properly_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Properly Nested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Widget__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/WidgetNestedValidationBatch.cls
/**
 * @description       : 
 * @author            : junior.lima
 * @group             : 
 * @last modified on  : 07-20-2021
 * @last modified by  : junior.lima
 * Modifications Log 
 * Ver   Date         Author        Modification
 * 1.0   07-20-2021   junior.lima   Initial Version
**/
global class WidgetNestedValidationBatch implements Database.batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
        /** SELECT WIDGETS RECORDS CREATED LAST HOUR **/
        DateTime lastHourDateTime = System.Now().addHours(-1);
        String query = 'SELECT  Id, Name, Batch_Updated__c, Is_Properly_Nested__c, Value__c FROM Widget__c WHERE CreatedDate >= :lastHourDateTime';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bd, List<Widget__c> listWidgetsLastHours)
    {
        System.debug(listWidgetsLastHours);

        for(Widget__c unitWidget : listWidgetsLastHours)
        {          
            /** USE THE GLOBAL MATCHER TO DEFINE IF IT IS NESTED OR NOT **/
            unitWidget.Batch_Updated__c = TRUE;
        }
        update listWidgetsLastHours;
    }
    global void finish(Database.BatchableContext bc)
    {
    }
}